# Personalize your website info here
title:            Kathryn Wallin-Miller
tagline:          Here to do science and chew bubble gum, and I'm all out of bubble gum.
description:      Insert Awesome Website Here.
url:              http://kathrynwallin.github.io
author:
  name:           Kathryn Wallin-Miller
  url:            https://twitter.com/anewguy

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
